# Generated by Django 5.2.6 on 2025-09-28 01:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConsentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "body",
                    models.TextField(
                        help_text="HTML body of the consent form (used to display the terms)"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ConsentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("treatment_date", models.DateField(help_text="Date of the treatment")),
                (
                    "treatment_type",
                    models.CharField(
                        help_text="E.g. Lash lift, Microblading, Facial", max_length=200
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        blank=True,
                        help_text="Optional structured answers to questions",
                        null=True,
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="consent_signatures/"
                    ),
                ),
                (
                    "typed_signature",
                    models.CharField(
                        blank=True,
                        help_text="Client typed name for signature",
                        max_length=255,
                    ),
                ),
                ("signed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="consent_pdfs/"),
                ),
                ("consent_given", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="consent_forms.client",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="consent_forms.consenttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
